UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"NumeroEspecializacion": "1", "Puntaje": "20"}' WHERE id=4;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"NumeroEspecializacion": "2", "Puntaje": "10"}' WHERE id=5;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"NumeroMaestria": "1", "NumeroEspecializacion": "1", "Puntaje": "40"}' WHERE id=6;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"NumeroMaestria": "1", "NumeroEspecializacion": "2", "Puntaje": "30"}' WHERE id=7;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"NumeroMaestria": "2", "NumeroEspecializacion": "1", "Puntaje": "20"}' WHERE id=8;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"NumeroMaestria": "1", "Puntaje": "80"}' WHERE id=9;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"NumeroMaestria": "0", "Puntaje": "120"}' WHERE id=10;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "A1", "Puntaje": "15"}' WHERE id=11;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "A2", "Puntaje": "12"}' WHERE id=12;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "B", "Puntaje": "8"}' WHERE id=13;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "C", "Puntaje": "3"}' WHERE id=14;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "A1", "Puntaje": "4,5"}' WHERE id=15;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "A2", "Puntaje": "3,6"}' WHERE id=16;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "B", "Puntaje": "2,4"}' WHERE id=17;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "C", "Puntaje": "0,9"}' WHERE id=18;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "A1", "Puntaje": "9"}' WHERE id=19;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "A2", "Puntaje": "7,2"}' WHERE id=20;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "B", "Puntaje": "4,8"}' WHERE id=21;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaRevista": "C", "Puntaje": "1,8"}' WHERE id=22;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"Alcance": "Nacional", "TipodeObraArtistica": "Creación Original", "Puntaje": "14"}' WHERE id=42;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"Alcance": "Nacional", "TipodeObraArtistica": "Creacion complementaria o de apoyo", "Puntaje": "8"}' WHERE id=43;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"Alcance": "Nacional", "TipodeObraArtistica": "Interpretacion de obra", "Puntaje": "8"}' WHERE id=44;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"Alcance": "Internacional", "TipodeObraArtistica": "Creación Original", "Puntaje": "20"}' WHERE id=45;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"Alcance": "Internacional", "TipodeObraArtistica": "Creacion complementaria o de apoyo", "Puntaje": "12"}' WHERE id=46;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"Alcance": "Internacional", "TipodeObraArtistica": "Interpretacion de obra", "Puntaje": "14"}' WHERE id=47;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaTesis": "Laureada", "Puntaje": "36"}' WHERE id=59;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaTesis": "Meritoria", "Puntaje": "32"}' WHERE id=60;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaTesis": "Aprobada", "Puntaje": "20"}' WHERE id=61;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaTesis": "Laureada", "Puntaje": "72"}' WHERE id=62;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaTesis": "Meritoria", "Puntaje": "70"}' WHERE id=63;
UPDATE produccion_academica.puntaje_subtipo_produccion SET caracteristicas= '{"CategoriaTesis": "Aprobada", "Puntaje": "62"}' WHERE id=64;