INSERT INTO produccion_academica.tipo_metadato(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, form_definition, fecha_creacion, fecha_modificacion) VALUES (87,'Tipo Universidad','Tipo de Universidad','TUNIV', true,87, '{"etiqueta": "select", "claseGrid":"col-6", "nombre": "87", "label_i18n": "tipo_universidad", "placeholder_i18n": "tipo_universidad", "requerido": true, "tipo": "number", "key": "Nombre", "opciones": [{"Id":"1","Nombre":"Nacional"},{"Id":"2","Nombre":"Extranjera"}],"span":""}', now(), now());
INSERT INTO produccion_academica.tipo_metadato(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, form_definition, fecha_creacion, fecha_modificacion) VALUES (88,'Titulo de convalidado','Titulo con que fue convalidado','NTCONV', true,88, '{"etiqueta":"input","claseGrid":"col-6","nombre":"88","label_i18n":"titulo_convalidado","placeholder_i18n":"titulo_convalidado","requerido":false,"tipo":"text","span":"Este dato solo se llena en caso de que el título sea convalidado por el Ministerio de Educación "}', now(), now());

ALTER TABLE produccion_academica.metadato_subtipo_produccion ADD COLUMN orden numeric(5,2);

UPDATE produccion_academica.metadato_subtipo_produccion SET orden=3 WHERE id=1;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=4 WHERE id=2;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=5 WHERE id=3;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=6 WHERE id=4;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=7 WHERE id=5;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=8 WHERE id=6;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=11 WHERE id=7;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=12 WHERE id=8;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=13 WHERE id=9;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=14 WHERE id=10;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=15 WHERE id=11;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=16 WHERE id=12;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=17 WHERE id=13;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=20 WHERE id=14;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=21 WHERE id=15;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=22 WHERE id=16;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=23 WHERE id=17;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=24 WHERE id=18;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=25 WHERE id=19;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=26 WHERE id=20;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=30 WHERE id=21;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=31 WHERE id=22;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=33 WHERE id=23;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=34 WHERE id=24;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=35 WHERE id=25;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=36 WHERE id=26;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=40 WHERE id=27;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=41 WHERE id=28;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=43 WHERE id=29;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=44 WHERE id=30;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=45 WHERE id=31;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=46 WHERE id=32;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=50 WHERE id=33;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=51 WHERE id=34;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=53 WHERE id=35;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=54 WHERE id=36;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=55 WHERE id=37;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=56 WHERE id=38;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=59 WHERE id=39;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=60 WHERE id=40;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=61 WHERE id=41;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=62 WHERE id=42;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=63 WHERE id=43;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=64 WHERE id=44;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=65 WHERE id=45;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=66 WHERE id=46;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=67 WHERE id=47;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=68 WHERE id=48;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=71 WHERE id=49;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=72 WHERE id=50;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=73 WHERE id=51;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=74 WHERE id=52;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=75 WHERE id=53;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=76 WHERE id=54;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=77 WHERE id=55;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=78 WHERE id=56;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=79 WHERE id=57;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=80 WHERE id=58;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=83 WHERE id=59;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=84 WHERE id=60;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=85 WHERE id=61;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=86 WHERE id=62;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=87 WHERE id=63;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=88 WHERE id=64;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=89 WHERE id=65;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=90 WHERE id=66;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=91 WHERE id=67;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=92 WHERE id=68;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=93 WHERE id=69;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=94 WHERE id=70;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=95 WHERE id=71;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=96 WHERE id=72;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=97 WHERE id=73;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=98 WHERE id=74;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=99 WHERE id=75;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=100 WHERE id=76;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=101 WHERE id=77;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=102 WHERE id=78;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=103 WHERE id=79;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=104 WHERE id=80;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=105 WHERE id=81;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=106 WHERE id=82;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=107 WHERE id=83;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=108 WHERE id=84;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=109 WHERE id=85;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=110 WHERE id=86;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=111 WHERE id=87;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=112 WHERE id=88;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=113 WHERE id=89;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=114 WHERE id=90;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=115 WHERE id=91;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=116 WHERE id=92;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=117 WHERE id=93;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=118 WHERE id=94;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=119 WHERE id=95;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=120 WHERE id=96;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=121 WHERE id=97;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=122 WHERE id=98;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=123 WHERE id=99;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=124 WHERE id=100;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=125 WHERE id=101;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=126 WHERE id=102;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=127 WHERE id=103;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=128 WHERE id=104;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=129 WHERE id=105;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=130 WHERE id=106;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=131 WHERE id=107;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=132 WHERE id=108;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=133 WHERE id=109;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=134 WHERE id=110;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=135 WHERE id=111;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=136 WHERE id=112;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=137 WHERE id=113;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=138 WHERE id=114;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=139 WHERE id=115;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=140 WHERE id=116;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=141 WHERE id=117;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=142 WHERE id=118;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=143 WHERE id=119;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=144 WHERE id=120;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=145 WHERE id=121;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=146 WHERE id=122;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=147 WHERE id=123;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=148 WHERE id=124;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=149 WHERE id=125;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=150 WHERE id=126;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=151 WHERE id=127;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=152 WHERE id=128;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=153 WHERE id=129;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=154 WHERE id=130;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=155 WHERE id=131;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=156 WHERE id=132;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=157 WHERE id=133;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=158 WHERE id=134;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=159 WHERE id=135;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=160 WHERE id=136;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=161 WHERE id=137;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=162 WHERE id=138;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=163 WHERE id=139;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=164 WHERE id=140;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=165 WHERE id=141;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=166 WHERE id=142;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=167 WHERE id=143;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=168 WHERE id=144;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=169 WHERE id=145;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=170 WHERE id=146;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=173 WHERE id=147;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=174 WHERE id=148;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=175 WHERE id=149;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=176 WHERE id=150;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=177 WHERE id=151;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=178 WHERE id=152;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=181 WHERE id=153;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=182 WHERE id=154;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=183 WHERE id=155;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=184 WHERE id=156;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=185 WHERE id=157;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=186 WHERE id=158;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=189 WHERE id=159;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=190 WHERE id=160;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=193 WHERE id=161;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=194 WHERE id=162;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=197 WHERE id=163;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=198 WHERE id=164;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=199 WHERE id=165;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=202 WHERE id=166;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=203 WHERE id=167;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=204 WHERE id=168;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=207 WHERE id=169;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=208 WHERE id=170;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=209 WHERE id=171;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=210 WHERE id=172;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=211 WHERE id=173;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=212 WHERE id=174;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=213 WHERE id=175;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=219 WHERE id=176;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=218 WHERE id=177;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=220 WHERE id=178;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=221 WHERE id=179;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=222 WHERE id=180;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=223 WHERE id=181;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=217 WHERE id=182;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=224 WHERE id=183;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=225 WHERE id=184;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=228 WHERE id=185;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=226 WHERE id=186;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=229 WHERE id=187;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=227 WHERE id=188;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=230 WHERE id=189;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=231 WHERE id=190;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=237 WHERE id=191;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=236 WHERE id=192;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=238 WHERE id=193;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=239 WHERE id=194;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=240 WHERE id=195;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=241 WHERE id=196;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=235 WHERE id=197;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=242 WHERE id=198;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=243 WHERE id=199;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=246 WHERE id=200;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=244 WHERE id=201;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=247 WHERE id=202;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=245 WHERE id=203;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=248 WHERE id=204;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=157 WHERE id=205;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=252 WHERE id=206;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=253 WHERE id=207;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=254 WHERE id=208;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=255 WHERE id=209;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=256 WHERE id=210;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=251 WHERE id=211;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=258 WHERE id=212;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=259 WHERE id=213;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=260 WHERE id=214;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=261 WHERE id=215;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=262 WHERE id=216;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=263 WHERE id=217;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=264 WHERE id=218;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=265 WHERE id=219;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=274 WHERE id=220;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=269 WHERE id=221;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=270 WHERE id=222;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=271 WHERE id=223;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=272 WHERE id=224;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=273 WHERE id=225;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=268 WHERE id=226;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=275 WHERE id=227;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=276 WHERE id=228;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=277 WHERE id=229;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=278 WHERE id=230;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=279 WHERE id=231;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=280 WHERE id=232;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=281 WHERE id=233;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=284 WHERE id=234;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=285 WHERE id=235;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=286 WHERE id=236;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=287 WHERE id=237;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=288 WHERE id=238;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=289 WHERE id=239;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=292 WHERE id=240;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=293 WHERE id=241;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=294 WHERE id=242;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=295 WHERE id=243;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=296 WHERE id=244;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=297 WHERE id=245;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=298 WHERE id=246;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=301 WHERE id=247;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=302 WHERE id=248;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=303 WHERE id=249;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=304 WHERE id=250;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=305 WHERE id=251;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=308 WHERE id=252;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=309 WHERE id=253;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=310 WHERE id=254;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=313 WHERE id=255;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=314 WHERE id=256;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=315 WHERE id=257;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=316 WHERE id=258;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=319 WHERE id=259;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=320 WHERE id=260;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=321 WHERE id=261;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=322 WHERE id=262;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=323 WHERE id=263;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=324 WHERE id=264;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=325 WHERE id=265;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=326 WHERE id=266;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=329 WHERE id=267;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=330 WHERE id=268;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=331 WHERE id=269;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=334 WHERE id=270;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=335 WHERE id=271;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=336 WHERE id=272;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=216 WHERE id=273;
UPDATE produccion_academica.metadato_subtipo_produccion SET orden=234 WHERE id=274;

INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (275,true,42,87,5, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (276,true,40,88,5, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (277,true,49,87,6, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (278,true,52,88,6, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (279,true,29,87,4, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (280,true,32,88,4, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (281,true,1,39,1, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (282,true,2,45,1, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (283,true,9,39,2, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (284,true,10,45,2, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (285,true,18,39,3, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (286,true,19,45,3, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (287,true,27,39,4, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (288,true,28,45,4, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (289,true,37,39,5, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (290,true,38,45,5, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (291,true,47,39,6, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (292,true,48,45,6, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (293,true,57,39,7, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (294,true,58,45,7, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (295,true,69,39,8, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (296,true,70,45,8, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (297,true,81,39,9, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (298,true,82,45,9, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (299,true,171,39,17, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (300,true,172,45,17, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (301,true,179,39,18, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (302,true,180,45,18, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (303,true,187,39,19, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (304,true,188,45,19, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (305,true,191,39,20, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (306,true,192,45,20, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (307,true,195,39,21, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (308,true,196,45,21, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (309,true,200,39,22, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (310,true,201,45,22, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (311,true,205,39,23, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (312,true,206,45,23, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (313,true,214,39,24, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (314,true,215,45,24, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (315,true,232,39,25, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (316,true,233,45,25, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (317,true,249,39,26, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (318,true,250,45,26, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (319,true,266,39,27, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (320,true,267,45,27, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (321,true,282,39,28, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (322,true,283,45,28, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (323,true,290,39,29, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (324,true,291,45,29, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (325,true,299,39,30, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (326,true,300,45,30, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (327,true,306,39,31, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (328,true,307,45,31, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (329,true,311,39,32, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (330,true,312,45,32, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (331,true,317,39,33, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (332,true,318,45,33, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (333,true,327,39,34, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (334,true,328,45,34, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (335,true,332,39,35, now(), now());
INSERT INTO produccion_academica.metadato_subtipo_produccion(id, activo, orden, tipo_metadato_id, subtipo_produccion_id, fecha_creacion, fecha_modificacion) VALUES (336,true,333,45,35, now(), now());