appname = produccion_academica_crud
httpport = ${PRODUCCION_ACADEMICA_CRUD_HTTP_PORT}
runmode = ${PRODUCCION_ACADEMICA_CRUD_RUN_MODE}

PGdb   = ${PRODUCCION_ACADEMICA_CRUD_PGDB}
PGpass = ${PRODUCCION_ACADEMICA_CRUD_PGPASS}
PGurls = ${PRODUCCION_ACADEMICA_CRUD_PGHOST}
PGport = ${PRODUCCION_ACADEMICA_CRUD_PGPORT}
PGuser = ${PRODUCCION_ACADEMICA_CRUD_PGUSER}
PGschemas = ${PRODUCCION_ACADEMICA_CRUD_PGSCHEMA}
logPath= ${PRODUCCION_ACADEMICA_CRUD_LOG}
autorender = false
copyrequestbody = true
EnableDocs = true


