appname = produccion_academica_crud
PGdb   = ${PRODUCCION_ACADEMICA_CRUD_PGDB}
PGpass = ${PRODUCCION_ACADEMICA_CRUD_PGPASS}
PGurls = ${PRODUCCION_ACADEMICA_CRUD_PGHOST}
PGuser = ${PRODUCCION_ACADEMICA_CRUD_PGUSER}
PGschemas = ${PRODUCCION_ACADEMICA_CRUD_PGSCHEMA}
httpport = ${PRODUCCION_ACADEMICA_CRUD_HTTP_PORT}
logPath= ${PRODUCCION_ACADEMICA_CRUD_LOG}
runmode = ${RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true


